/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nuix.examples;

import org.junit.jupiter.api.Test;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class EngineVersionTest {
    private static final Logger LOG = LogManager.getLogger(EngineVersionTest.class);

    @Test
    void engineVersionCanBeRetrieved() {
        EngineVersion classUnderTest = new EngineVersion();
        LOG.info("Version is: {}", classUnderTest.getVersion());
        assertNotNull(classUnderTest.getVersion());
    }
}
