/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nuix;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import com.nuix.tools.NuixTools;

public class App {
    private static final Logger LOG = LogManager.getLogger(App.class);

    public String getGreeting() { return "Hello World!"; }

    public static void main(String[] args) {
        App app = new App();
        NuixTools.banner();
    }
}
